name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - run: dotnet publish --configuration Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: UEVR
          path: ${{github.workspace}}/UEVR/bin/Release/net6.0-windows/win-x64/publish/*.*
          if-no-files-found: error
          
      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5
        with:
            repo: uevr-frontend
            path: frontend
            owner: joeyhodge
            name: ${{format('UEVR frontend {0} ({1})', github.run_number, github.sha)}}
            tag: ${{format('frontend-{0}-{1}', github.run_number, github.sha)}}
            artifacts: "${{github.workspace}}/${{matrix.target}}.zip,${{github.workspace}}/${{matrix.target}}.zip.sha256"
            makeLatest: true
